type: go

up:
  - go:
      version: 1.18.2
  - homebrew:
    - gh
    - golangci-lint:
        version: 1.45.2


commands:
  revs:
    run: go run main.go
  release:
    run: scripts/release $@
  style:
    run: golangci-lint run "$@"
  tidy:
    run: go mod tidy
  test:
    run: go test -v ./...
